# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\x12\x07\x65xample\"/\n\x11HelloWorldRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\"\n\x12HelloWorldResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"2\n\x10\x45ogClientRequest\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x05\"\x9e\x01\n\x11\x45ogServerResponse\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\t\x12\x37\n\tdirection\x18\x02 \x01(\x0e\x32$.example.EogServerResponse.Direction\">\n\tDirection\x12\n\n\x06\x43\x45NTER\x10\x00\x12\x06\n\x02UP\x10\x01\x12\x08\n\x04\x44OWN\x10\x02\x12\x08\n\x04LEFT\x10\x03\x12\t\n\x05RIGHT\x10\x04\x32U\n\x0cHelloService\x12\x45\n\nHelloWorld\x12\x1a.example.HelloWorldRequest\x1a\x1b.example.HelloWorldResponse2U\n\x10\x45ogSignalService\x12\x41\n\x08\x43lassify\x12\x19.example.EogClientRequest\x1a\x1a.example.EogServerResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOWORLDREQUEST._serialized_start=25
  _HELLOWORLDREQUEST._serialized_end=72
  _HELLOWORLDRESPONSE._serialized_start=74
  _HELLOWORLDRESPONSE._serialized_end=108
  _EOGCLIENTREQUEST._serialized_start=110
  _EOGCLIENTREQUEST._serialized_end=160
  _EOGSERVERRESPONSE._serialized_start=163
  _EOGSERVERRESPONSE._serialized_end=321
  _EOGSERVERRESPONSE_DIRECTION._serialized_start=259
  _EOGSERVERRESPONSE_DIRECTION._serialized_end=321
  _HELLOSERVICE._serialized_start=323
  _HELLOSERVICE._serialized_end=408
  _EOGSIGNALSERVICE._serialized_start=410
  _EOGSIGNALSERVICE._serialized_end=495
# @@protoc_insertion_point(module_scope)
